<html>

<head>

    <title>纸色免费纸巾</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link rel="shortcut icon" href="/assets/header_logo.png" >

    <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.7.2/css/amazeui.min.css">

    <!-- <link rel="stylesheet" href="css/style.css"> -->

    <link rel="stylesheet" href="/css/index.css">

    <link rel="stylesheet" href="/css/animate.css">  


</head>


<body>
<!--
<div class="loader" id='loader'>
	<div class="loader-inner">
		<div class="loader-line-wrap">
			<div class="loader-line"></div>
		</div>
		<div class="loader-line-wrap">
			<div class="loader-line"></div>
		</div>
		<div class="loader-line-wrap">
			<div class="loader-line"></div>
		</div>
		<div class="loader-line-wrap">
			<div class="loader-line"></div>
		</div>
		<div class="loader-line-wrap">
			<div class="loader-line"></div>
		</div>
	</div>
</div> -->

<script type='text/javascript'>
    //监听加载状态改变
    // document.onreadystatechange = completeLoading;

    //加载状态为complete时移除loading效果
    // function completeLoading() {
    //     if (document.readyState == "complete") {
    // 		console.log(document.readyState);
    //         var loadingMask = document.getElementById('loader');
    //         loadingMask.parentNode.removeChild(loadingMask);
    //     }
    // }

    function active(event){

        $('.active').removeClass('active');

        var rel = $(event).attr('rel');
        console.log(rel);
        $('.'+rel).addClass('active');


        if(document.getElementsByClassName('active').length < 1){

            $('.first').addClass('active');
        }
    }
</script>

<div class='main'>

    <div class="header wow bounceInUp">
        <a href="#" name='first'></a>
        <img src="/assets/first.jpg" alt="" class="first" width="100%">

        <img src="/assets/header_logo.png" alt="" class='header_logo'>

        <nav class="nav_header wow bounceInDown">
            <a href="#first" class="first active" rel="first" onclick="active(this)">首页</a>
            <a href="#second" onclick="active(this)" rel="second" class="second">纸色·价值观</a>
            <a href="#third" class="third" rel="third" onclick="active(this)">纸色·合作加盟</a>
            <a href="#fourth" class="five" rel="five" onclick="active(this)">纸色·广告投放</a>
            <a href="#five" class="seven" rel="seven" onclick="active(this)">纸色·联系我们</a>
        </nav>
    </div>


    <a href="#" name="second"></a>
    <img src="/assets/second.jpg" alt="" class="second wow bounceInDown" width="100%">
    <a href="#" name="third"></a>
    <img src="/assets/third.jpg" alt="" class="fourth wow bounceInDown" width="100%">
    <a href="#" name="fourth"></a>
    <img src="/assets/fourth.jpg" alt="" class="five wow bounceInUp" width="100%">
    <a href="#" name="five"></a>
    <img src="/assets/five.jpg" alt="" class="seven wow bounceInUp" width="100%">

    <div class="footer wow bounceInDown">

        <a href="#" name="footer"></a>
        <!-- <img src="/assets/footer.png" alt="" class="footer" width="100%"> -->
        <img src="/assets/footer_logo.png" alt="footer_logo" class="footer_logo" width="5%">

        <nav class="nav_footer wow bounceInUp">
            <a href="#first" class="first active" rel="first" onclick="active(this)">首页</a>
            <a href="#second" onclick="active(this)" rel="second" class="second">纸色·价值观</a>
            <a href="#third" class="third" rel="third" onclick="active(this)">纸色·合作加盟</a>
            <a href="#five" class="five" rel="five" onclick="active(this)">纸色·广告投放</a>
            <a href="#seven" class="seven" rel="seven" onclick="active(this)">纸色·联系我们</a>
        </nav>

        <ul class="left_text_view wow slideInLeft">
            <li>电话：<span>400 1399 330</span></li>
            <li>地址：<span>广州市海珠区黄埔古港历史文化景观区石基路528号首层</span></li>
            <li>商业咨询邮件：<span>E-mail.IQGOGO@yeah.net</span></li>
        </ul>

        <ul class="right_text_view wow slideInRight">
            <li>公司名称：<span>广州智谷科技有限责任公司</span></li>
            <li>工商登记号码：<span>563-81-00723</span></li>
        </ul>

        <div class="IP_text">Copyright 广州智谷科技有限公司All rights reserved. 粤ICP备18042175号-1</div> -->

    </div>



</div>

<a href="#first" id="gototop" title="回到顶部" class="am-icon-arrow-up am-active" rel='first ' style="position: fixed;bottom: 5%;right: 1%;"></a>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="/js/wow.min.js"></script>
<script src="/js/elevator.min.js"></script>

<script type='text/javascript'>

    $(function(){


        var locationHref = window.location.href;

        var hrefArr = ['first','second','third','five','seven'];

        $('.active').removeClass('active');

        for (var i = 0; i < hrefArr.length; i++) {
            if(locationHref.indexOf(hrefArr[i]) !== -1){
                $('.'+hrefArr[i]).addClass('active');
            }
        }


        if(document.getElementsByClassName('active').length < 1){

            $('.first').addClass('active');
        }
    })

    new WOW().init();

    $('#gototop').hide();

    $(window).scroll(function() {
        if ($(window).scrollTop() >= 300) {
            $('#gototop').fadeIn(600);
        } else {
            $('.gototop').fadeOut(600);
        }
    });

    $('#gototop').click(function(){
        $("html,body").animate({
            scrollTop: 0
        }, 500);

        active(this);
    });


</script>


</body>

</html>