<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">-->


    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/index.js"></script>

    <title>智谷科技</title>
    <style type="text/css">
        a {
            text-decoration: none;
        }

        a:hover {
            text-decoration: none;
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .div-img img:hover {
            border: border: solid 2px #0f9ae0 \9;
            border-color: rgba(82, 168, 236, 1);
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(102, 175, 233, 1);
        }

        p {
            padding: 0px;
        }

        @-webkit-keyframes progress-bar-1 {
            from {
                width: 0%;
            }
            to {
                width: 25%;
            }
        }

        @-webkit-keyframes progress-bar-2 {
            from {
                width: 0%;
            }
            to {
                width: 25%;
            }
        }

        @-webkit-keyframes progress-bar-3 {
            from {
                width: 0%;
            }
            to {
                width: 50%;
            }
        }

        .progress.active .progress-bar-1 {
            -webkit-animation: progress-bar-1 1s linear;
            animation: progress-bar-1 1s linear;
        }

        .progress.active .progress-bar-2 {
            -webkit-animation: progress-bar-2 1s linear;
            animation: progress-bar-2 1s linear;
        }

        .progress.active .progress-bar-3 {
            -webkit-animation: progress-bar-3 1s linear;
            animation: progress-bar-3 1s linear;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }
    </style>
</head>
<body onscroll="scrollMain()" style="font-size: 70%;">
<?php include  __DIR__.'/../ex/page_header.phtml';?>
<!-- main body -->
<div id="main_content">
    <div>
        <div class="container pt-5 pb-5">
            <!-- 地址信息 -->
            <div class="container pl-5 pr-5">
                <div class="border">
                    <div id="allmap" style="height: 400px;width: 100%border:1px solid red !important;"></div>
                    <div class="border-right border-left pt-3 pl-3">
                        <div class="align-middle">
                            <label class="border d-inline-block float-left" style="border-radius: 3px;">
                                <div class="text-center">
                                    <i class="fa fa-map-marker fa-2x text-dark"></i>
                                </div>
                                <div class="font-weight-bold border-top pl-2 pr-2 pt-1 pb-1 text-white"
                                     style="background-color: #31E076;">NAME
                                </div>
                            </label>
                            <label class="font-weight-bold float-left d-inline-block pt-4 pl-4"
                                   style="font-size: 120%;">广州智谷科技有限责任公司</label>
                            <div class="clearfix"></div>
                        </div>
                        <p>
                            广州智谷科技有限公司，是一家以物联网技术为核心，集研发、生产、商务、运营、服务于一体的物联网智能高新技术企业。
                            纸色免费纸巾机是智谷科技旗下的创新互联网科技项目之一。该项目整合媒体、广告等资源，旨在为广大民众提供便利的生活环境，为广告商提供更为便捷有效的宣传渠道。纸色项目一直坚持独有的运营方式，做到真正意义上的便民、环保、公益。我们希望，纸色能够让全中国的纸巾不再付费使用，让市民真正生活在便利、绿色的家园中。
                        </p>
                        <div>
                            <span class="font-weight-bold">地址：</span>
                            <span class="font-weight-bold">广州市海珠区黄埔古港历史文化景观区石基路528-2号首层</span>
                        </div>
                        <div class="pt-5 pb-5">
                            <button onclick="mapAdress()" type="button"
                                    class="btn btn-outline-secondary font-weight-bold text-dark">路 线 查 询
                            </button>
                        </div>
                    </div>
                </div>
                <div class="p-3"></div>
                <div class="border">
                    <div class="pt-3 pl-3 row pb-3">
                        <div class="col-sm-6 col-md col-lg col-xl">
                            <div class="align-middle">
                                <label class="border d-inline-block float-left" style="border-radius: 3px;">
                                    <div class="text-center">
                                        <i class="fa fa-user fa-2x text-dark"></i>
                                    </div>
                                    <div class="font-weight-bold border-top pl-1 pr-1 pt-1 pb-1 text-white"
                                         style="background-color: #31E076;font-size: 75%;">CONTACT
                                    </div>
                                </label>
                                <label class="font-weight-bold float-left d-inline-block pt-4 pl-4"
                                       style="font-size: 120%;">联系我们</label>
                                <div class="clearfix"></div>
                            </div>
                            <p class="pt-2">
                                欢迎扫码添加纸色客服微信号，或致电纸色全国服务热线，咨询更多详情。
                            </p>
                            <div class="row">
                                <a class="d-inline-block" href="#">
                                    <img src="/static/img/buttons/phone.png"/>
                                    <span class="d-inline-block fa-2x pt-3 pl-3">400-1399-330</span>
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md col-lg col-xl row pt-5">
                            <div class="col-sm-6 col-md col-lg col-xl text-center">
                                <img src="/static/img/qrCode/kefu.jpg" class="img-responsive center-block"
                                     style="width: 80%;"/>
                                <p class="text-center pt-3" style="font-size: 80%;">客服微信号</p>
                            </div>
                            <div class="col-sm-6 col-md col-lg col-xl text-center">
                                <img src="/static/img/qrCode/weixin.jpg" class="img-responsive center-block"
                                     style="width: 80%;"/>
                                <p class="text-center pt-3" style="font-size: 80%;">官方微信公众号</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include __DIR__ . '/../ex/page_footer.phtml'; ?>

    <script type="application/javascript" src="/static/js/map.js"></script>
    <script type="application/javascript" src="/static/js/main.js"></script>
    <script>
        loadJScript();
    </script>
</body>
</html>
