<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">-->

    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/index.js"></script>
    <title>智谷科技</title>

    <style>
        img, body {
            padding: 0px;
            margin: 0px;
        }

        #allmap {
            width: 100%;
            height: 100%;
            overflow: hidden;
            margin: 0;
            font-family: "微软雅黑";
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        /*.navbar-nav a{
            background-color: #000;
            opacity: 1;
            z-index: 4;
        }*/
        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .dropdown-item:hover {
            background-color: #6502F6;
        }

        .fa-angle:hover {
            background-color: #999 !important;
            color: #fff !important;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }

        @media screen and (max-width: 550px) {
            .angle_l, .angle_r {
                display: none !important;
            }
        }

        @media screen and (min-width: 550px) {
            .angle_l, .angle_r {
                display: inline-block !important;
            }
        }
    </style>
</head>
<body onscroll="scroll()" style=" font-size: 70%;">

<nav id="header_2" class="navbar  navbar-light bg-faded pb-0 transparent "
     style="display:none;position: fixed;z-index: 3;width: 100%;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation" style="margin:0 auto;">
        <span>
            <i class="fa fa-bars text-white"></i>
        </span>
    </button>
    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav text-center" style="font-size: 100%">
            <a href="/front/view/index" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1 navSelect">首页</span>
            </a>
            <a href="/front/view/" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">品牌动态</span>
            </a>
            <a onclick="tips()" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">商务合作</span>
            </a>
            <a href="/front/view/successList" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">成功案例</span>
            </a>
            <a href="/front/view/team" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">团队资讯</span>
            </a>
            <a href="/front/view/contact" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">联系我们</span>
            </a>
        </div>
    </div>
</nav>
<div style="position: relative;">
    <!-- 导航栏 -->
    <div id="header" class="text-center pt-2 transparent" style="position: absolute;z-index: 2;width:100%;">
        <div>
            <img src="/static/img/index/logo.png" class="img-responsive center-block" style="width:5rem;"/>
        </div>
        <div class="row m-0">
            <div class="col-sm-12">
                <nav class="navbar navbar-expand-sm navbar-toggler-md navbar-light bg-faded pb-0">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                            data-target="#navbarNavAltMarkup1" aria-controls="navbarNavAltMarkup1" aria-expanded="false"
                            aria-label="Toggle navigation" style="margin:0 auto;">
					    	<span>
					    		<i class="fa fa-bars text-white"></i>
					    	</span>
                    </button>
                    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup1">
                        <div class="navbar-nav text-center" style="font-size: 100%">
                            <a href="/front/view/index" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1 navSelect">首页</span>
                            </a>
                            <a onclick="tips()" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">品牌动态</span>
                            </a>
                            <a onclick="tips()" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">商务合作</span>
                            </a>
                            <a href="/front/view/successList" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">成功案例</span>
                            </a>
                            <a href="/front/view/team" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">团队资讯</span>
                            </a>
                            <a href="/front/view/contact" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">联系我们</span>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
<!--    		<div id="main_footer" class="text-center align-center" style="background-color:rgba(0,0,0,0.7);position: absolute;z-index: 2;width:100%;bottom: 0;max-height: 25%;">-->
<!--    			<div class="container">-->
<!--    				<div class="row">-->
<!--    					<div class="angle_l col-sm-3 text-center m-auto pt-1 pb-1" style="max-width: 20%;">-->
<!--    						<span class="fa-angle d-inline-block bg-white text-center pl-3 pr-3 pt-1 pb-1 text-dark" href="#carousel-example-generic" role="button" data-slide="prev" style="border-radius: 4px;">-->
<!--    							<i class="fa fa-angle-left fa-2x"></i>-->
<!--    						</span>-->
<!--    					</div>-->
<!--    					<div id="carousel-example-generic" class="col-sm-6 carousel slide" data-ride="carousel">-->
<!--    					  <div class="carousel-inner text-white" role="listbox">-->
<!--    					    <div class="carousel-item active">-->
<!--    					    	<p class="text-left pb-1 m-auto" style="overflow: hidden;text-overflow: ellipsis;margin: 0px;font-size: 60%;max-height: 30px;white-space: nowrap;">-->
<!--    								<span class="btn font-weight-bold pl-1 pr-1" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>&nbsp;-->
<!--    								<span class="font-weight-light">Today,there is another successful financing of Zhise 20 million., there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.</span>-->
<!--    							</p>-->
<!--    							<p class="text-left pt-1 m-auto" style="overflow: hidden;text-overflow: ellipsis;margin；0px;font-size: 60%;max-height: 30px;white-space: nowrap;">-->
<!--    								<span class="btn font-weight-bold pl-1 pr-1" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>&nbsp;-->
<!--    								<span>Today,there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.</span>-->
<!--    							</p>-->
<!--    					    </div>-->
<!--    					    <div class="carousel-item">-->
<!--    					    	<p class="text-left pb-1 m-auto" style="overflow: hidden;text-overflow: ellipsis;margin: 0px;font-size: 60%;max-height: 30px;white-space: nowrap;">-->
<!--    								<span class="btn font-weight-bold pl-1 pr-1" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>&nbsp;-->
<!--    								<span class="font-weight-light">Today,there is another successful financing of Zhise 20 million., there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.</span>-->
<!--    							</p>-->
<!--    							<p class="text-left pt-1 m-auto" style="overflow: hidden;text-overflow: ellipsis;margin；0px;font-size: 60%;max-height: 30px;white-space: nowrap;">-->
<!--    								<span class="btn font-weight-bold pl-1 pr-1" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>&nbsp;-->
<!--    								<span>Today,there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.</span>-->
<!--    							</p>-->
<!--    					    </div>-->
<!--    					    <div class="carousel-item">-->
<!--    					    	<p class="text-left pb-1 m-auto" style="overflow: hidden;text-overflow: ellipsis;margin: 0px;font-size: 60%;max-height: 30px;white-space: nowrap;">-->
<!--    								<span class="btn font-weight-bold pl-1 pr-1" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>&nbsp;-->
<!--    								<span class="font-weight-light">Today,there is another successful financing of Zhise 20 million., there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.</span>-->
<!--    							</p>-->
<!--    							<p class="text-left pt-1 m-auto" style="overflow: hidden;text-overflow: ellipsis;margin；0px;font-size: 60%;max-height: 30px;white-space: nowrap;">-->
<!--    								<span class="btn font-weight-bold pl-1 pr-1" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>&nbsp;-->
<!--    								<span>Today,there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.Today, there is another successful financing of Zhise 20 million.</span>-->
<!--    							</p>-->
<!--    					    </div>-->
<!--    					  </div>-->
    <!-- 图片切换 -->
    <div id="main_content">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="/static/img/index/slide1.png" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="/static/img/index/slide2.png" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="/static/img/index/slide3.png" alt="Third slide">
                </div>
            </div>
        </div>
    </div>
</div>

<?php include __DIR__ . '/../ex/page_footer.phtml'; ?>


<script type="text/javascript">
    $(function () {
        $("img").addClass("carousel-inner img-responsive img-rounded");
        $("#myCarousel").carousel({
		interval:3000,
		pause:false
	});
    });
</script>

</body>
</html>
