<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">-->


    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/font.css"/>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/index.js"></script>

    <title>智谷科技</title>
    <style type="text/css">
        a {
            text-decoration: none;
        }

        a:hover {
            text-decoration: none;
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .div-img img:hover {
            border: border: solid 2px #0f9ae0 \9;
            border-color: rgba(82, 168, 236, 1);
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(102, 175, 233, 1);
        }

        p {
            padding: 0px;
        }

        @-webkit-keyframes progress-bar-1 {
            from {
                width: 0%;
            }
            to {
                width: 25%;
            }
        }

        @-webkit-keyframes progress-bar-2 {
            from {
                width: 0%;
            }
            to {
                width: 25%;
            }
        }

        @-webkit-keyframes progress-bar-3 {
            from {
                width: 0%;
            }
            to {
                width: 50%;
            }
        }

        .progress.active .progress-bar-1 {
            -webkit-animation: progress-bar-1 1s linear;
            animation: progress-bar-1 1s linear;
        }

        .progress.active .progress-bar-2 {
            -webkit-animation: progress-bar-2 1s linear;
            animation: progress-bar-2 1s linear;
        }

        .progress.active .progress-bar-3 {
            -webkit-animation: progress-bar-3 1s linear;
            animation: progress-bar-3 1s linear;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }
    </style>
</head>
<body onscroll="scrollMain()" style="font-family: 'PingFang-Regular';font-size: 70%;">
<?php include  __DIR__.'/../ex/page_header.phtml';?>
<!-- main body -->
<div id="main_content">
    <div class="container-fluid">
        <div class="row text-center pt-4">
            <h2 class="col-sm-12 font-weight-bold">多场景应用</h2>
            <p class="col-sm-12" style="font-size: 70%;">可满足多场景经营的可能性</p>
        </div>
        <div class="container-fluid pl-5 pr-5 pb-5">
            <div class="row text-center">
                <div class="col-sm col-lg col-xl"></div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success1.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success2.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success3.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl"></div>
            </div>
            <div class="row text-center">
                <div class="col-sm col-lg col-xl"></div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success4.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success5.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success6.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl"></div>
            </div>
            <div class="row text-center">
                <div class="col-sm col-lg col-xl"></div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success7.jpg" class="img-responsive center-block"
                         style="width: 100%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success8.jpg" class="img-responsive center-block"
                         style="width: 100%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success9.jpg" class="img-responsive center-block"
                         style="width: 100%;">
                </div>
                <div class="col-sm col-lg col-xl"></div>
            </div>
        </div>
    </div>
    <!-- something -->
    <div class="pt-5 pb-5"
         style="background: url(/static/img/bg/bg-footer.png);-moz-background-size:100% 100%;background-size:100% 100%;background-repeat:no-repeat;">
        <div class="container">
            <div class="row text-center pl-5 pr-5">
                <div class="col-sm-2 "></div>
                <div class="col-sm-4 text-left row pl-5 pt-3">
                    <h6 class="font-weight-bold">SOMETHING</h6>
                    <p style="font-size: 60%;">Lorem ipsum dolor. consectectetuer adipiscing elit. sed
                        diamnonummy nibh euismod tincidunt ut laoreet dolore
                        magna ali quam suscupt lobortis nust ut aliquip ex ea
                        commodo consequat.
                    </p>
                </div>
                <div class="col-sm-1"></div>
                <div class="col-sm-4  pt-3 text-left">
                    <div class="pb-1">
                        <span class="font-weight-bold" style="font-size: 60%;">school district</span>
                        <div class="progress bg-white">
                            <div class="progress-bar bg-success progress-bar-1" role="progressbar" style="width: 25%"
                                 aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <div class="pb-1">
                        <span class="font-weight-bold" style="font-size: 60%;">Administrative Area</span>
                        <div class="progress bg-white">
                            <div class="progress-bar bg-success progress-bar-2" role="progressbar" style="width: 25%"
                                 aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <div class="pb-1">
                        <span class="font-weight-bold" style="font-size: 60%;">Dining area</span>
                        <div class="progress bg-white">
                            <div class="progress-bar bg-success progress-bar-3" role="progressbar" style="width: 50%"
                                 aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php include __DIR__ . '/../ex/page_footer.phtml'; ?>

    <script type="application/javascript" src="/static/js/main.js"></script>
</body>
</html>
