<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">-->


    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/index.js"></script>

    <title>智谷科技</title>
    <style type="text/css">
        a {
            text-decoration: none;
        }

        a:hover {
            text-decoration: none;
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .div-img img:hover {
            border: border: solid 2px #0f9ae0 \9;
            border-color: rgba(82, 168, 236, 1);
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(102, 175, 233, 1);
        }

        p {
            padding: 0px;
        }

        @-webkit-keyframes progress-bar-1 {
            from {
                width: 0%;
            }
            to {
                width: 25%;
            }
        }

        @-webkit-keyframes progress-bar-2 {
            from {
                width: 0%;
            }
            to {
                width: 25%;
            }
        }

        @-webkit-keyframes progress-bar-3 {
            from {
                width: 0%;
            }
            to {
                width: 50%;
            }
        }

        .progress.active .progress-bar-1 {
            -webkit-animation: progress-bar-1 1s linear;
            animation: progress-bar-1 1s linear;
        }

        .progress.active .progress-bar-2 {
            -webkit-animation: progress-bar-2 1s linear;
            animation: progress-bar-2 1s linear;
        }

        .progress.active .progress-bar-3 {
            -webkit-animation: progress-bar-3 1s linear;
            animation: progress-bar-3 1s linear;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }
    </style>
</head>
<body onscroll="scrollMain()" style="font-size: 70%;">
<?php include  __DIR__.'/../ex/page_header.phtml';?>
<!-- main body -->
<div id="main_content">
    <div>
        <!-- 项目简介 -->
        <div class="pt-5 pb-5 " style="font-size: 130%;background-color: #F1F1F1 ;">
            <div class="row text-center m-0">
                <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1 text-right"></div>
                <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4 text-center">
                    <img class="img-responsive rounded-circle" style="width: 65%;min-width: 240px;"
                         src="/static/img/team/team_1.jpg">
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 text-left" style="font-family: 'PingFang-Regular';font-size: 70%;">
                    <p class="font-weight-bold fa-2x m-0">项目简介</p>
                    <p class="pt-2">
                        纸色是近年迅速崛起并蓬勃发展的创新互联网科技项目。纸色团队由一群心怀梦想、<br/>
                        满怀热情的年轻人组成，坚持以先进的技术、卓越的产品、良好的信誉服务大众，<br/>
                        致力于满足广大民众对美好智能未来生活的畅想和期待。
                    </p>
                    <p>
                        我们期待通过纸色项目，整合媒体、广告、环保公益力量等资源，为广大民众提供<br/>
                        便利、舒适、富有正能量的优质生活环境，为广告合作商提供更为便捷有效的宣传<br/>
                        渠道。我们希望，纸色能够让全中国的纸巾不再付费使用，让市民真正生活在便利、<br/>
                        绿色的家园中。
                    </p>
                </div>
                <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
            </div>
        </div>
        <!-- 项目理念 -->
        <div class="pt-5 pb-5">
            <div class="row m-0">
                <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                <div class="col-sm-5 col-md-5 col-lg-5 col-xl-5 text-left">
                    <div class="">
                        <p class="font-weight-bold fa-2x m-0">项目理念</p>
                        <p class="pt-2 m-0 font-weight-bold">便民利民——永久免费，你需要时我就在</p>
                        <p class="pt-2 m-0">
                            纸色通过采用“至柔至韧”的维达手帕纸，为大众提供卓越、精益的产品与用户体验；<br/>
                            同时，计划在全国范围内投放20万台纸巾设备，两年内纸色免费纸巾机将遍布全国<br/>
                            各类人流密集场所，让广大民众随时随地免费领取纸巾。
                        </p>
                        <p class="pt-2 m-0 font-weight-bold">倡导环保——杜绝浪费，共建绿色社会</p>
                        <p class="pt-2 m-0">
                            纸色强调社会责任感，提倡绿色环保，杜绝铺张浪费的理念。每人每天仅可免费领<br/>
                            取一包纸巾，以此培养公民节约能源、低碳环保的意识，降低对环境的破坏，维护<br/>
                            地球生态的平衡。
                        </p>
                        <p class="pt-2 m-0 font-weight-bold">心怀公益——取之于树，还之于树</p>
                        <p class="pt-2 m-0">
                            植树造林，再不只是植树节的独特仪式，人人皆可献力。纸色承诺，每送出50包纸<br/>
                            巾，我们将会捐赠1棵小树苗至植树部门。同时，个人额外付费购买纸巾的收入也将<br/>
                            被捐赠至社会公益组织。
                        </p>
                        <p class="pt-2 m-0">
                            纸色计划与全国范围内的环保机构、各大高校联合举办公益环保活动，传播“取之于<br/>
                            树，还之于树”的生态保护理念。
                        </p>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 col-lg-3 col-xl-3 text-center pt-5">
                    <img class="img-responsive rounded-circle" style="width: 85%;min-width: 240px;"
                         src="/static/img/team/team_2.jpg">
                </div>
            </div>
        </div>
        <!-- 团队合作 -->
        <div class="pt-5 pb-5" style="background-color: #F1F1F1 ;font-family: 'PingFang-Regular';font-size: 70%;">
            <div class="row text-center m-0">
                <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1 text-right"></div>
                <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4 text-center">
                    <img class="img-responsive rounded-circle" style="width: 65%;min-width: 240px;;"
                         src="/static/img/team/team_3.jpg">
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 text-left pt-5">
                    <p class="font-weight-bold fa-2x m-0">团队文化</p>
                    <p class="pt-2 m-0 font-weight-bold">
                        纸色团队——带有奉献，勇敢，使命与拼搏精神的狼性团队
                    </p>
                    <p class="pt-2 m-0">
                        贪：对工作、对事业的“贪性”，无止境地去探索； <br/>
                        狠：把工作中的困难毫不留情地克服掉、消灭； <br/>
                        野：工作中、事业开拓中不要命的拼搏精神； <br/>
                        暴：粗暴地对待一个又一个难关，不对难关保留任何仁慈。
                    </p>
                </div>
                <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
            </div>
        </div>
    </div>

    <?php include __DIR__.'/../ex/page_footer.phtml';?>

    <script type="application/javascript" src="/static/js/main.js"></script>
</body>
</html>
