<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>纸色免费纸巾</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico"/>
    <link href="/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!--    <link href="/dist/css/questions.css" rel="stylesheet" />-->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.min.css">

    <style>
        input::-webkit-input-placeholder {
            /* placeholder颜色  */
            color: #ccc;
            /* placeholder字体大小  */
            font-size: 12px;
        }
        textarea::-webkit-input-placeholder {
            /* placeholder颜色  */
            color: #ccc;
            /* placeholder字体大小  */
            font-size: 12px;
        }
        .tipRed{
            border: border:solid 1px red \9;border-color:rgba(82,168,236,0.8);box-shadow:0 1px 1px red inset, 0 0 8px red;
        }
    </style>

</head>