<div class="pb-5" style="font-size: 100%;background-color: rgb(101,2,246);">
    <div class="container pl-5 pr-5 pt-5 text-white">
        <div class="row">
            <div class="col-6 border-right border-white pr-lg-4">
                <div class="float-lg-right">
                    <div class="row">
                        <span>全国咨询热线：</span>
                        <span>400-1399-330</span>
                    </div>
                    <div class="row">
                        <span>地址：</span>
                        <span>广州市海珠区黄埔古港历史文化景观区石基路528-2号首层</span>
                    </div>
                    <div class="row">
                        <span>商业咨询邮件：</span>
                        <span>IQGOGO@yeah.net</span>
                    </div>
                    <div class="row">
                        <span>客服热线：</span>
                        <span>180-2713-3575</span>
                    </div>
                    <div class="row">
                        <span>公司名称：</span>
                        <span>广州智谷科技有限责任公司</span>
                    </div>
                    <div class="row">
                        <span>工商登记号码：</span>
                        <span>563-81-00723</span>
                    </div>
                </div>
            </div>
            <div class="col-6 pl-lg-3">
                <div class="float-left pl-2">
                    <div class="row">
                        <span>Service hotline:</span>
                        <span>400-1399-330</span>
                    </div>
                    <div class="row">
                        <span>Address:</span>
                        <span>G/F, No.528-2, SHI JI Road, Haizhu district, Guangzhou</span>
                    </div>
                    <div class="row">
                        <span>E-mail:</span>
                        <span>IQgogo@yeah.net</span>
                    </div>
                    <div class="row">
                        <span>Company:</span>
                        <span>IQgogo Technology Co., Ltd</span>
                    </div>
                    <div class="pt-2">
                        <i class="fa fa-weibo pr-2 fa-2x"></i>
                        <i class="fa fa-qq pr-2 fa-2x"></i>
                        <i class="fa fa-weixin fa-2x"></i>
                    </div>
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
        <div class="text-center text-white pt-5 pb-3" style="font-size: 8px;">
            <span>Copyright 广州智谷科技有限公司All rights reserved. 粤ICP备16059531号-1</span>
        </div>
    </div>
</div>

<div class="modal fade" id="tips">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <i class="fa fa-smile-o text-danger fa-3x"></i>温馨提示
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body text-center">
                小猿正在努力开发中... ...
            </div>

            <!-- 模态框底部 -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
            </div>

        </div>
    </div>
</div>
